library(readr)
setwd("/home/jc/Documents")
Rodrigo <- read_csv("Rodrigo.csv")

PerLead <- na.omit(Rodrigo[c(22:26, 28:31)])

library(psych)
pairs.panels(PerLead, 
             method = "spearman", 
             hist.col = "lightgreen",
             density = TRUE,  
             ellipses = TRUE,
             pch = 21,
             cex = 5.5,
             cex.axis = 1.8,
             cex.labels = 2.5,
             lwd = 2,
             rug = TRUE,
             stars = TRUE
)

#
# This is the Confirmatory Factor Analysis for Personality
library(lavaan)
modelData <- PerLead
model<-"
! regressions 
   Personality=~Personality__P1*P1
   Personality=~Personality__P2*P2
   Personality=~Personality__P3*P3
   Personality=~Personality__P4*P4
! residuals, variances and covariances
   P1 ~~ VAR_P1*P1
   P2 ~~ VAR_P2*P2
   P3 ~~ VAR_P3*P3
   P4 ~~ VAR_P4*P4
   Personality ~~ 1.0*Personality
! observed means
   P1~1;
   P2~1;
   P3~1;
   P4~1;
";
result1 <- lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
result1b <- lavaan(model, data=modelData, fixed.x=FALSE, missing="listwise", estimator = "DWLS");
summary(result1, fit.measures=TRUE);
summary(result1b, fit.measures=TRUE);

library(semTable)
semTable(list("Personality (M1)" = result1, "Personality (M2)" = result1b),
         columns = c ("estse", "z", "p"), 
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         table.float = TRUE, 
         longtable = FALSE, 
         caption = "Veamos",
         label = "t0")

library(semPlot)
semPaths(result, whatLabels = "std", layout = "tree", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)


# This is the Confirmatory Factor Analysis for Leadership

#
# This model specification was automatically generated by Onyx
#
modelData <- PerLead
model2<-"
! regressions 
   Leadership=~Leadership__L1*L1
   Leadership=~Leadership__L2*L2
   Leadership=~Leadership__L3*L3
   Leadership=~Leadership__L4*L4
   Leadership=~Leadership__L5*L5
! residuals, variances and covariances
   Leadership ~~ 1.0*Leadership
   L1 ~~ VAR_L1*L1
   L2 ~~ VAR_L2*L2
   L3 ~~ VAR_L3*L3
   L4 ~~ VAR_L4*L4
   L5 ~~ VAR_L5*L5
! observed means
   L1~1;
   L2~1;
   L3~1;
   L4~1;
   L5~1;
";
result2 <- lavaan(model2, data=modelData, fixed.x=FALSE, missing="FIML");
result2b <- lavaan(model2, data=modelData, fixed.x=FALSE, missing="listwise", estimator = "DWLS");
summary(result2, fit.measures=TRUE);
summary(result2b, fit.measures=TRUE);

semTable(list("Personality (M1)" = result2, "Personality (M2)" = result2b),
         columns = c ("estse", "z", "p"), 
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         table.float = TRUE, 
         longtable = FALSE, 
         caption = "Veamos",
         label = "t2")

semPaths(result2, whatLabels = "std", layout = "tree", color = list(
   lat = rgb(255, 100, 118, maxColorValue = 255),
   man = rgb(155, 253, 175, maxColorValue = 255)),
   mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)


fit2 <- semTable (result2, columns = c("est" , "se" , "p"), paramSets = c("loadings"), fits = c("chisq", "rmsea") , file =
                     "fit1", longtable = FALSE, table.float=TRUE, caption = "Table Floated ( not a longtable )", label = "tab:fit1.t3 ")

# Modelo Estructural Personality-Leadership

#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- PerLead ;
model3<-"
! regressions 
   Leadership=~Leadership__L1*L1
   Leadership=~Leadership__L2*L2
   Leadership=~Leadership__L3*L3
   Leadership=~Leadership__L4*L4
   Leadership=~Leadership__L5*L5
   Personality=~x1__P1*P1
   Personality=~x1__P2*P2
   Personality=~x1__P3*P3
   Personality=~x1__P4*P4
   Personality=~Personality__Leadership*Leadership
! residuals, variances and covariances
   Leadership ~~ 1.0*Leadership
   L1 ~~ VAR_L1*L1
   L2 ~~ VAR_L2*L2
   L3 ~~ VAR_L3*L3
   L4 ~~ VAR_L4*L4
   L5 ~~ VAR_L5*L5
   P1 ~~ VAR_P1*P1
   P2 ~~ VAR_P2*P2
   P3 ~~ VAR_P3*P3
   P4 ~~ VAR_P4*P4
   Personality ~~ 1.0*Personality
! observed means
   L1~1;
   L2~1;
   L3~1;
   L4~1;
   L5~1;
   P1~1;
   P2~1;
   P3~1;
   P4~1;
";
result3 <- lavaan(model3, data=modelData, fixed.x=FALSE, missing="listwise", estimator = "PML");
summary(result3, fit.measures=TRUE);

semPaths(result3, whatLabels = "std", layout = "tree", color = list(
   lat = rgb(255, 100, 118, maxColorValue = 255),
   man = rgb(155, 253, 175, maxColorValue = 255)),
   mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)


fit1.t1 <- semTable(result3, columns = c("estse" , "p"), 
                    paramSets = c("loadings", "residualvariances",
                    "latentcovariances"),
                    fits = c("chisq", "rmsea", "cfi", "tli"),
                    type = "latex", table.float = TRUE, 
                    caption = "Cualquier Vaina", 
                    label = "t2", longtable = FALSE)
